# Generated by Django 5.2.3 on 2025-07-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdevnewsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blogdevnewsapp.etiqueta'),
        ),
    ]
